### ISSUE TITLE
undefined method `red' for " ZRO":String

### ISSUE THREAD

**Issue by jonathantribouharet** [zhandao/zero-rails_openapi#15]
Hi,
I just created a rails 5.2 (rc2) application and added your gem and I have the following error in a empty controller:

```
undefined method `red' for " ZRO":String
Rails.root: /app

Application Trace | Framework Trace | Full Trace
zero-rails_openapi (1.5.6) lib/open_api/dsl.rb:39:in `api'
app/controllers/api/houseworks_controller.rb:5:in `<class:HouseworksController>'
app/controllers/api/houseworks_controller.rb:3:in `<main>'
bootsnap (1.2.1) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:84:in `load'
bootsnap (1.2.1) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:84:in `load'
```

Here my controllers:

```
require 'open_api/dsl'

class Api::ApiController < ActionController::API
  include OpenApi::DSL
end
```

```
class Api::HouseworksController < Api::ApiController
  api :index, 'GET list' do
  end
end
```

This is can fix if I add `require 'colorize'` in my HouseworksController.
I think you can avoid this by set the require in your lib.

**Comment by zhandao** [comment]
Hi,
I tried to require colorize. Could you install the latest version from GitHub, and test this problem?
`gem 'zero-rails_openapi', github: 'zhandao/zero-rails_openapi'`

**Comment by jonathantribouharet** [comment]
Yes it works.
Thanks

**Comment by zhandao** [comment]
You are welcome.
