### ISSUE TITLE
Multiple API Specs in same project?

### ISSUE THREAD

**Issue by barnaclebarnes** [zhandao/zero-rails_openapi#26]
Is there a way to generate 2 separate API specs in the same Rails project? We have 2 separate API's (different end points, different authentication, etc) that we want to generate 2 separate documents for.

**Comment by zhandao** [comment]
2 files or 2 specs in the same file？

**Comment by barnaclebarnes** [comment]
2 separate files. So we basically want 2 separate versions of the initialiser in your examples.

**Comment by zhandao** [comment]
In your initializer:
```ruby
OpenApi::Config.tap do |c|
  c.instance_eval do
    open_api :spec_one, base_doc_class: DocBaseClassOne
    info: # set spec one's info
    ...

    open_api :spec_two, base_doc_class: DocBaseClassTwo
    info: # set spec two's info
    ...
  end

# OR

  c.open_api_docs = {
    spec_one: { },
    sepc_two: { }
  }
end
```
[About Configure](https://github.com/zhandao/zero-rails_openapi#configure)

**Comment by zhandao** [comment]
Did you try it?

**Comment by barnaclebarnes** [comment]
@zhandao Yes I did and it worked. I'm just trying now to separate out my docs into separate files at the moment. When you say:

```
# config/initializers/open_api.rb
# in your configuration
base_doc_class: ApiDoc

# app/api_doc/api_doc.rb
require 'open_api/dsl'

class ApiDoc < Object
  include OpenApi::DSL
end

# app/api_doc/v1/examples_doc.rb
class V1::ExamplesDoc < ApiDoc
  route_base 'api/v1/examples'

  api :index do
    # ...
  end
end
```

```class ApiDoc < Object```

is `Object` here meant to be the base class, not just `Object`? I was getting a controller_name error when I just had Object here.

**Comment by zhandao** [comment]
Please show me the "controller_name error"?

**Comment by zhandao** [comment]
Did you require or load `the/path/to/api_doc` when your rails application is starting (or before you run `write_docs`)?

**Comment by barnaclebarnes** [comment]
hen I use:

```
require 'open_api/dsl'

class WriteApiDoc < Object 
  include OpenApi::DSL

  components do
  end
end
```

```
# bin/rails console
/Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/bundler/gems/zero-rails_openapi-798bcffc600e/lib/open_api/dsl.rb:21:in `doc_tag': undefined local variable or method `controller_name' for WriteApiDoc:Class (NameError)
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/bundler/gems/zero-rails_openapi-798bcffc600e/lib/open_api/dsl.rb:28:in `components'
	from /Users/barnacle/Documents/mytours-web/app/api_doc/write_api_doc.rb:6:in `<class:WriteApiDoc>'
	from /Users/barnacle/Documents/mytours-web/app/api_doc/write_api_doc.rb:3:in `<top (required)>'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:476:in `load'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:476:in `block in load_file'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:661:in `new_constants_in'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:475:in `load_file'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:374:in `block in require_or_load'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:36:in `block in load_interlock'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/concurrency/share_lock.rb:149:in `exclusive'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:11:in `loading'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:36:in `load_interlock'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:357:in `require_or_load'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:510:in `load_missing_constant'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:202:in `const_missing'
	from /Users/barnacle/Documents/mytours-web/config/initializers/open_api.rb:42:in `block in <top (required)>'
	from /Users/barnacle/Documents/mytours-web/config/initializers/open_api.rb:3:in `tap'
	from /Users/barnacle/Documents/mytours-web/config/initializers/open_api.rb:3:in `<top (required)>'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `block in load'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:655:in `block in load_config_initializer'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/notifications.rb:168:in `instrument'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:654:in `load_config_initializer'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:611:in `each'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:611:in `block in <class:Engine>'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `run'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:59:in `block in run_initializers'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/2.4.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/2.4.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:48:in `each'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:48:in `tsort_each_child'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/2.4.0/tsort.rb:415:in `call'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/2.4.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/2.4.0/tsort.rb:347:in `each'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/2.4.0/tsort.rb:347:in `call'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:58:in `run_initializers'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/application.rb:353:in `initialize!'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/railtie.rb:185:in `public_send'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/railtie.rb:185:in `method_missing'
	from /Users/barnacle/Documents/mytours-web/config/environment.rb:5:in `<top (required)>'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/application.rb:329:in `require_environment!'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/command/actions.rb:16:in `require_application_and_environment!'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/commands/console/console_command.rb:96:in `perform'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/command/base.rb:63:in `perform'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/command.rb:44:in `invoke'
	from /Users/barnacle/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
	from bin/rails:8:in `require'
	from bin/rails:8:in `<main>'
```

Seems to run fine if I have:

```
require 'open_api/dsl'

class WriteApiDoc < Api::FrontendV2::BaseController 
  include OpenApi::DSL

  components do
  end
end
```

**Comment by zhandao** [comment]
If you want to write Api spec defination somewhere else for reducing the line numbers of controller, you need to:
1. create a class, like ApiDoc, and make it `include OpenApi::DSL` (then it could be the base class for writing Api spec).
2. set the specified Api spec's base_doc_class to ApiDoc.
3. let your doc class (like `V1::ExamplesDoc`) inherit the base_doc_class (ApiDoc).
4. set the `route_base` (to route path `api/v1/examples` of that controller `Api::V1::ExamplesController`) inside `V1::ExamplesDoc`.

These four steps are necessary. And I'll update the REAMDE.

**Comment by barnaclebarnes** [comment]
But I think that is what I have done:

```
   write_api: {
      base_doc_class: WriteApiDoc,

      info: {
        title: 'My Tours App Write APIs',
        description: 'API documentation for the My Tours write API',
      servers: [
       {
          url: 'https://app.mytoursapp.com',
          description: 'API server'
        }
      ]
    }

class FrontendV2::UploadedFilesDoc < WriteApiDoc
  route_base 'api/frontend_v2/uploaded_files'

  api(:show, "This API gets a files metadata", id: "UploadedFileShow") do
    self[:tags] = ["mytours"]  

    param :query, :hash, String, :req, desc: 'Hash of the file to get'

    response '200', 'success', :json, data: :UploadedFile
  end

  api(:create, "Upload a file to the server", id: "UploadedFileCreate") do
    self[:tags] = ["mytours"]  

    response '200', 'success', :json, data: :UploadedFile
  end

end
```

It is the `class WriteApiDoc < Object` that is the thing causing the issue. Inheriting from `Object` doesn't seem to expose `controller_name` anywhere.

**Comment by zhandao** [comment]
Yes, if you define `route_base`, `@doc_tag` will be set, then the `controller_name` will not be called. So:
```ruby
require 'open_api/dsl'

class WriteApiDoc < Object 
  include OpenApi::DSL

  components do
  end
end
```
will raise not_method error.

**Comment by zhandao** [comment]
So this issue is done?

**Comment by barnaclebarnes** [comment]
👍
