### ISSUE TITLE
OpenApi.write_doc failing for routes.

### ISSUE THREAD

**Issue by sonam-gupta** [zhandao/zero-rails_openapi#27]
Error Stack
```
Uncaught exception: undefined method `match?' for #<String:0x007fe9c6186e80>
Did you mean?  match
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/zero-rails_openapi-1.5.7/lib/open_api/generator.rb:88:in `block in routes_list'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/zero-rails_openapi-1.5.7/lib/open_api/generator.rb:87:in `map'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/zero-rails_openapi-1.5.7/lib/open_api/generator.rb:87:in `routes_list'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/zero-rails_openapi-1.5.7/lib/open_api/dsl.rb:67:in `ctrl_routes_list'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/zero-rails_openapi-1.5.7/lib/open_api/dsl.rb:39:in `api'
	/Users/sonamgup/work_dir/orca/app/controllers/api/services_controller.rb:12:in `<class:ServicesController>'
	/Users/sonamgup/work_dir/orca/app/controllers/api/services_controller.rb:1:in `<top (required)>'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:457:in `load'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:457:in `block in load_file'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:647:in `new_constants_in'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:456:in `load_file'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:354:in `require_or_load'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:494:in `load_missing_constant'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:184:in `const_missing'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.8/lib/active_support/inflector/methods.rb:263:in `const_get'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.8/lib/active_support/inflector/methods.rb:263:in `block in constantize'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.8/lib/active_support/inflector/methods.rb:259:in `each'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.8/lib/active_support/inflector/methods.rb:259:in `inject'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.8/lib/active_support/inflector/methods.rb:259:in `constantize'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.8/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/zero-rails_openapi-1.5.7/lib/open_api/generator.rb:19:in `block in generate_docs'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/zero-rails_openapi-1.5.7/lib/open_api/generator.rb:18:in `each'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/zero-rails_openapi-1.5.7/lib/open_api/generator.rb:18:in `generate_docs'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/zero-rails_openapi-1.5.7/lib/open_api/generator.rb:54:in `write_docs'
	/Users/sonamgup/work_dir/orca/config/initializers/open_api.rb:19:in `<top (required)>'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `block in load'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/railties-4.2.8/lib/rails/engine.rb:652:in `block in load_config_initializer'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/railties-4.2.8/lib/rails/engine.rb:651:in `load_config_initializer'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/railties-4.2.8/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/railties-4.2.8/lib/rails/engine.rb:615:in `each'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/railties-4.2.8/lib/rails/engine.rb:615:in `block in <class:Engine>'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
	/Users/sonamgup/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	/Users/sonamgup/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	/Users/sonamgup/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	/Users/sonamgup/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	/Users/sonamgup/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `each'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `tsort_each_child'
	/Users/sonamgup/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:415:in `call'
	/Users/sonamgup/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
	/Users/sonamgup/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	/Users/sonamgup/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:347:in `each'
	/Users/sonamgup/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:347:in `call'
	/Users/sonamgup/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	/Users/sonamgup/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	/Users/sonamgup/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
	/Users/sonamgup/work_dir/orca/config/environment.rb:5:in `<top (required)>'
	/Users/sonamgup/work_dir/orca/config.ru:3:in `require'
	/Users/sonamgup/work_dir/orca/config.ru:3:in `block in <main>'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/rack-1.6.10/lib/rack/builder.rb:55:in `instance_eval'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/rack-1.6.10/lib/rack/builder.rb:55:in `initialize'
	/Users/sonamgup/work_dir/orca/config.ru:in `new'
	/Users/sonamgup/work_dir/orca/config.ru:in `<main>'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/rack-1.6.10/lib/rack/builder.rb:49:in `eval'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/rack-1.6.10/lib/rack/builder.rb:49:in `new_from_string'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/rack-1.6.10/lib/rack/builder.rb:40:in `parse_file'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/rack-1.6.10/lib/rack/server.rb:300:in `build_app_and_options_from_config'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/rack-1.6.10/lib/rack/server.rb:209:in `app'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/railties-4.2.8/lib/rails/commands/server.rb:61:in `app'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/rack-1.6.10/lib/rack/server.rb:337:in `wrapped_app'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/railties-4.2.8/lib/rails/commands/server.rb:139:in `log_to_stdout'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/railties-4.2.8/lib/rails/commands/server.rb:78:in `start'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:75:in `tap'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:75:in `server'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	/Users/sonamgup/.rvm/gems/ruby-2.3.4/gems/railties-4.2.8/lib/rails/commands.rb:17:in `<top (required)>'
	/Users/sonamgup/work_dir/orca/bin/rails:9:in `require'
	/Users/sonamgup/work_dir/orca/bin/rails:9:in `<top (required)>'
```

**Comment by zhandao** [comment]
To solve it:
1. Upgrade your ruby version to >= 2.4
2. monkey patch:
  ```ruby
  class String
    def match?(pattern)
      !match(pattern).nil?
    end
  end
  ```

**Comment by sonam-gupta** [comment]
Routes:
```
Rails.application.routes.draw do
  ActiveModelSerializers.config.adapter = :json_api
  namespace :api do
    get  "/version", to: "base#version", as: "version"
    get  "/health", to: "base#health", as: "health"
    get  "/build_vars", to: "base#build_vars", as: "build_vars"
    get  "/service_status", to: "base#service_status", as: "service_status"
    get  "/test_connectivity_vault", to: "base#test_api_vault_connectivity", as: "test_api_vault_connectivity"
    resources :services, only: [:index, :create]
    get "/services/:id/fd_apps", to: "fd_apps#index"
    get "/services/:id/fd_apps/:fd_app_id/fd_images", to: "fd_images#index"
    get "/services/:id/fd_apps/:fd_app_id/fd_images/:fd_image_id/labels", to: "fd_images#labels"
    get "/services/:id/fd_apps/:fd_app_id/fd_images/:fd_image_id/default_env_vars", to: "fd_images#default_env_vars"
    scope module: "users" do
      get "/repositories", to: "users#repositories", as: "repositories"
    end
    scope module: "resources" do
      get "/clusters", to: "clusters#index", as: "index"
      get "/regions", to: "cluster_regions#index", as: "cluster_regions_index"
      get "/services/:id/images", to: "artifactory#images", as: "artifactory_images"
    end
  end
end
```

API Definintion
```
doc_tag name: "Services", desc: "ServicesController APIs"
  route_base '/api/services'

  components do
    schema :Service, type: :Service
  end

  api :index do
    resp(200,
         "success",
         :json,
         data: { service: :Service })
  end
```

**Comment by sonam-gupta** [comment]
Ok, issue resolved. I think its because of route base, removing that helped it. Thanks :)

**Comment by zhandao** [comment]
OK, thanks to use.
