### ISSUE TITLE
'block in load_missing_constant': uninitialized constant OpenApi

### ISSUE THREAD

**Issue by mits87** [zhandao/zero-rails_openapi#46]
Hi,

I'm trying use your gem but when I copy 1:1 some basic example from readme then I got an error:

```/app/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:76:in `block in load_missing_constant': uninitialized constant OpenApi (NameError)```

The problem is appearing when I try run a server: `rails s` with configuration file:

`config/initializers/open_api.rb`
```
require 'open_api'

OpenApi::Config.class_eval do
  # Part 1: configs of this gem
  self.file_output_path = 'public/open_api'

  # Part 2: config (DSL) for generating OpenApi info
  open_api :doc_name, base_doc_classes: [ApiDoc]
  info version: '1.0.0', title: 'Homepage APIs'#, description: ..
  # server 'http://localhost:3000', desc: 'Internal staging server for testing'
  # bearer_auth :Authorization
end
```

I will appreciate for help.

**Comment by zhandao** [comment]
Gemfile and full error stack information please?

**Comment by mits87** [comment]
**application.rb**

```require_relative 'boot'

require "rails"
require "active_model/railtie"
require "active_job/railtie"
require "active_record/railtie"
require "action_controller/railtie"
require "action_mailer/railtie"
require "action_view/railtie"

Bundler.require(*Rails.groups)

module UsersIdentityProvider
  class Application < Rails::Application
    config.load_defaults 5.2
    config.api_only = true
    config.eager_load_paths << "#{Rails.root}/lib"
  end
end
```

**Gemfile**
```
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.3'

gem 'rails', '~> 5.2.2'
gem 'mysql2', '>= 0.4.4', '< 0.6.0'
gem 'puma', '~> 3.11'
gem 'bootsnap', '>= 1.1.0', require: false
gem 'rack-cors', '~> 1.0.2'

group :development, :test do
  gem 'rspec-rails', '~> 3.8'
  gem 'pry-rails'
  gem 'awesome_print'
end

group :development do
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'active_model_serializers', '~> 0.10.0'

gem 'devise', '~> 4.5.0'
gem 'devise-jwt', '~> 0.5.8'
gem 'sentry-raven', '~> 2.9.0'
gem 'shoryuken', '~> 4.0'
gem 'aws-sdk-sqs', '~> 1.3'
gem 'zero-rails_openapi'
```

**Full Trace**
```
DB_PASSWORD=root rails s
=> Booting Puma
=> Rails 5.2.2 application starting in development
=> Run `rails server -h` for more startup options
Exiting
Traceback (most recent call last):
	81: from bin/rails:3:in `<main>'
	80: from bin/rails:3:in `load'
	79: from /home/ruby/app/bin/spring:15:in `<top (required)>'
	78: from /home/ruby/app/bin/spring:15:in `require'
	77: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
	76: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
	75: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
	74: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
	73: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
	72: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
	71: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
	70: from /home/ruby/app/bin/rails:9:in `<top (required)>'
	69: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	68: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	67: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
	66: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	65: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	64: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/commands.rb:18:in `<main>'
	63: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/command.rb:46:in `invoke'
	62: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/command/base.rb:65:in `perform'
	61: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	60: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	59: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	58: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:142:in `perform'
	57: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:142:in `tap'
	56: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	55: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:51:in `start'
	54: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:89:in `log_to_stdout'
	53: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/rack-2.0.6/lib/rack/server.rb:354:in `wrapped_app'
	52: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:27:in `app'
	51: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/rack-2.0.6/lib/rack/server.rb:219:in `app'
	50: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/rack-2.0.6/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	49: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/rack-2.0.6/lib/rack/builder.rb:40:in `parse_file'
	48: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/rack-2.0.6/lib/rack/builder.rb:49:in `new_from_string'
	47: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/rack-2.0.6/lib/rack/builder.rb:49:in `eval'
	46: from config.ru:in `<main>'
	45: from config.ru:in `new'
	44: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/rack-2.0.6/lib/rack/builder.rb:55:in `initialize'
	43: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/rack-2.0.6/lib/rack/builder.rb:55:in `instance_eval'
	42: from config.ru:3:in `block in <main>'
	41: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require_relative'
	40: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	39: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	38: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
	37: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	36: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	35: from /home/ruby/app/config/environment.rb:5:in `<main>'
	34: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
	33: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
	32: from /home/ruby/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	31: from /home/ruby/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	30: from /home/ruby/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	29: from /home/ruby/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `call'
	28: from /home/ruby/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `each'
	27: from /home/ruby/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
	26: from /home/ruby/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
	25: from /home/ruby/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:415:in `call'
	24: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/initializable.rb:50:in `tsort_each_child'
	23: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/initializable.rb:50:in `each'
	22: from /home/ruby/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	21: from /home/ruby/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
	20: from /home/ruby/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	19: from /home/ruby/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	18: from /home/ruby/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
	17: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
	16: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
	15: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
	14: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/engine.rb:613:in `block in <class:Engine>'
	13: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/engine.rb:613:in `each'
	12: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
	11: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/engine.rb:656:in `load_config_initializer'
	10: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/notifications.rb:170:in `instrument'
	 9: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/engine.rb:657:in `block in load_config_initializer'
	 8: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	 7: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	 6: from /home/ruby/app/config/initializers/open_api.rb:3:in `<main>'
	 5: from /home/ruby/app/config/initializers/open_api.rb:3:in `class_eval'
	 4: from /home/ruby/app/config/initializers/open_api.rb:8:in `block in <main>'
	 3: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:58:in `load_missing_constant'
	 2: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:76:in `rescue in load_missing_constant'
	 1: from /home/ruby/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
/home/ruby/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:76:in `block in load_missing_constant': uninitialized constant ApiDoc (NameError)
```

**Comment by zhandao** [comment]
The error at the top of the stack is `uninitialized constant ApiDoc`?

The setting `base_doc_classes` should be an array of base classes of the classes you write the OpenApi spec in, like `[ActionController::Base]` (if you write spec in controllers).

**Comment by mits87** [comment]
Ahh yes! Thank you

**Comment by zhandao** [comment]
👌

**Comment by amitdotagarwal** [comment]
I am facing the same issue, could you please explain me what is 

> The error at the top of the stack is `uninitialized constant ApiDoc`?
> 
> The setting `base_doc_classes` should be an array of base classes of the classes you write the OpenApi spec in, like `[ActionController::Base]` (if you write spec in controllers).

Could you please explain, what piece of code is needed to fix this issue?

**Comment by zhandao** [comment]
@amitdotagarwal How do you write OpenApi DSL? (please show the code)

**Comment by amitdotagarwal** [comment]
# in config/initializers/open_api.rb
require 'open_api'

OpenApi::Config.class_eval do
  # Part 1: configs of this gem
  self.file_output_path = 'public/open_api'

  # Part 2: config (DSL) for generating OpenApi info
  base_doc_classes =[]
  open_api :doc_name, base_doc_classes: [ApiDoc]
  info version: '1.0.0', title: 'Homepage APIs'#, description: ..
  # server 'http://localhost:3000', desc: 'Internal staging server for testing'
  # bearer_auth :Authorization
end

**Comment by zhandao** [comment]
@amitdotagarwal Emmm ... Do you know what is `OpenApi`, and why do you use this gem?

**Comment by amitdotagarwal** [comment]
I am using this for to generate docs for the API.

**Comment by zhandao** [comment]
Do you write OpenApi code in controllers?

**Comment by amitdotagarwal** [comment]
No, all code outside main application.

**Comment by zhandao** [comment]
I don't understand, what does "outside main application" mean?

**Comment by amitdotagarwal** [comment]
I mean I am trying to create one application by using this gem, and this gem will call other application to generate the API docs.
